const Map localization = {
  'en': {
    'menu': {
      'play': 'Play',
      'settings': 'Settings',
    },
    'theme': {
      'theme0': 'Oriental Cherry',
      'theme1': 'Toffee',
      'theme2': 'Sand Blues',
    },
    'settings' : {
      'autosave' : 'Autosave',
      'on' : 'On',
      'off' : 'Off',
      'change' : 'Change',
      'theme' : 'Theme',
      'language' : 'Language',
      'currentlang' : 'English',
      'syncprog' : 'Synchronise progress',
      'eraseprog' : 'Erase progress',
      'erase' : 'Erase',
      'confirmationtext' : 'Do you want to erase progress?',
      'flushtext' : 'Database deleted, progress erased!',
    },
    'selection' : {
      'selection' : 'Puzzle selection',
      'completed' : 'Completed',
      'selectionconfirmation' : 'Would you like to play level',
      'load' : 'LOAD SAVE',
    },
    'game' : {
      'save' : 'SAVE',
      'character' : 'Character',
      'pronunciation' : 'Pronunciation',
      'meaning' : 'Meaning',
      'examples' : 'Examples',
      'defeattitle' : 'DEFEAT',
      'defeatmessage' : 'Would you like to try again?',
    },
    'general' : {
      'lives' : 'Lives',
      'unlimited' : 'Unlimited',
      'yes' : 'Yes',
      'no' : 'No',
      'settings' : 'Settings',
    },
    'picross' : {
      0 : {
        'Test' : 'Test',
        'Lol' : 'Lol',
        'Taxi driver' : 'Taxi driver',
        'Rerekumkum' : 'Rerekumkum',
      },
      1 : {
        'Hajle Selassie' : 'Hajle Selassie',
        'La' : 'La',
        'Ma' : 'Ma',
        'Wa' : 'Wa',
      },
      2 : {
        'Work' : 'Work',
        'Too' : 'Too',
        'Lazy' : 'Lazy',
        'To think' : 'To think',
      },
      3 : {
        'New' : 'New',
        'News' : 'News',
        'Newspaper' : 'Newspaper',
        'Newsr' : 'Newsr',
      },
      4 : {
        'Nothing' : 'Nothing',
        'Nie' : 'Nie',
        'Nein' : 'Nein',
        'No' : 'No',
      },
      5 : {
        'Obtain' : 'Obtain',
        'Ob' : 'Ob',
        'Ta' : 'Ta',
        'In' : 'In',
      },
      6 : {
        'Pleasure' : 'Pleasure',
        'Happy' : 'Happy',
        'Joy' : 'Joy',
        'Optimistic' : 'Optimistic',
      },
      7 : {
        'Silver' : 'Silver',
        'Bank' : 'Bank',
        'Milky Way' : 'Milky Way',
        'Screen' : 'Screen',
      }
    }
  },

  'pl': {
    'menu': {
      'play': 'Graj',
      'settings': 'Ustawienia',
    },
    'theme': {
      'theme0': 'Wiśnia Orientu',
      'theme1': 'Toffi',
      'theme2': 'Blues Piasków',
    },
    'settings' : {
      'autosave' : 'Autozapis',
      'on' : 'Wł.',
      'off' : 'Wył.',
      'change' : 'Zmień',
      'theme' : 'Motyw',
      'language' : 'Język',
      'currentlang' : 'polski',
      'syncprog' : 'Synchronizuj postępy',
      'eraseprog' : 'Wymaż postępy',
      'erase' : 'Wymaż',
      'confirmationtext' : 'Czy chcesz wymazać wszelkie postępy?',
      'flushtext' : 'Dane usunięte, postęp wymazany!',
    },
    'selection' : {
      'selection' : 'Wybór zagadki',
      'completed' : 'Ukończono',
      'selectionconfirmation' : 'Czy chcesz rozwiązać zagadkę o numerze',
      'load' : 'UŻYJ ZAPISU',
    },
    'game' : {
      'save' : 'ZAPISZ',
      'character' : 'Znak',
      'pronunciation' : 'Wymowa',
      'meaning' : 'Znaczenie',
      'examples' : 'Przykłady',
      'defeattitle' : 'KLĘSKA',
      'defeatmessage' : 'Czy chcesz spróbować ponownie?',
    },
    'general' : {
      'lives' : 'Życia',
      'unlimited' : 'Nieskończone',
      'yes' : 'Tak',
      'no' : 'Nie',
      'settings' : 'Ustawienia',
    },
    'picross' : {
      0 : {
        'Test' : 'Test',
        'Lol' : 'Lol',
        'Taxi driver' : 'Taxi driver',
        'Rerekumkum' : 'Rerekumkum',
      },
      1 : {
        'Hajle Selassie' : 'Kazimierz Wielki',
        'La' : 'Koko',
        'Ma' : 'Spoko',
        'Wa' : 'Maroko',
      },
      2 : {
        'Work' : 'Work',
        'Too' : 'Too',
        'Lazy' : 'Lazy',
        'To think' : 'To think',
      },
      3 : {
        'New' : 'Nowy',
        'News' : 'Wiadomości',
        'Newspaper' : 'Gazeta',
        'Newsr' : 'Wiadomościr',
      },
      4 : {
        'Nothing' : 'Nic',
        'Nie' : 'Nie',
        'Nein' : 'Nein',
        'No' : 'No',
      },
      5 : {
        'Obtain' : 'Zdobyć',
        'Ob' : 'Ob',
        'Ta' : 'Ta',
        'In' : 'In',
      },
      6 : {
        'Pleasure' : 'Przyjemność',
        'Happy' : 'Szczęśliwy',
        'Joy' : 'Radość',
        'Optimistic' : 'Optymistyczny',
      },
      7 : {
        'Silver' : 'Srebro',
        'Bank' : 'Bank',
        'Milky Way' : 'Droga Mleczna',
        'Screen' : 'Ekran',
      },
    },
  },
};
