import 'package:chinese_picross/utilities/models/game.dart';
import 'package:chinese_picross/utilities/models/description.dart';
import 'package:chinese_picross/utilities/models/picross.dart';
import 'package:chinese_picross/utilities/models/example.dart';

List<Picross> picrossList = [
  Picross(
      number: 0,
      game: Game(
        correctTiles: [0, 2, 5, 6, 10, 12, 14, 21, 22, 23, 24, 25, 26, 27, 28, 29, 32, 34, 45, 50, 55, 56, 57, 58, 59, 60, 62, 63, 64, 65, 67, 69, 70, 72, 75, 76, 77, 78, 79, 80, 82, 85, 87, 89, 90, 92, 95, 96, 97, 98, 99],
        gameNumber: 0,
      ),
      description: Description(
          character: '福', chinesePronunciation: '​fú', meaning: 'Luck'),
      examples: [
        Example(word: '幸福', meaning: 'Well-being'),
        Example(word: '祝福', meaning: 'Wish well'),
        Example(word: '福利', meaning: 'Material benefit'),
      ]),
  Picross(
      number: 1,
      game: Game(
        correctTiles: [34, 35, 44, 45],
        gameNumber: 1,
      ),
      description: Description(
          character: 'A',
          chinesePronunciation: 'ba',
          meaning: 'Hajle Selassie'),
      examples: [
        Example(word: '出租车司机', meaning: 'La'),
        Example(word: '出租车司机', meaning: 'Ma'),
        Example(word: '出租车司机', meaning: 'Wa'),
        Example(word: '司机', meaning: 'Driver')
      ]),
  Picross(
      number: 2,
      game: Game(
        gameNumber: 2,
        correctTiles: [9, 10, 12, 14, 16, 19, 21, 22, 24, 26, 28, 29, 32, 33, 36, 37, 40, 41, 42, 43, 44, 45, 46, 52, 53, 56, 57, 61, 62, 63, 66, 67, 68, 70, 72, 74, 76, 79, 80, 82, 84, 86, 89, 99]
      ),
      description: Description(
          character: '类', chinesePronunciation: 'lèi', meaning: 'Kind'),
      examples: [
        Example(word: '类型', meaning: 'Type'),
        Example(word: '类似', meaning: 'Similar'),
        Example(word: '类别', meaning: 'Category'),
      ]),
  Picross(
      number: 3,
      game: Game(
        gameNumber: 3,
        correctTiles: [
          1,
          3,
          7,
          11,
          12,
          13,
          15,
          19,
          20,
          21,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          31,
          32,
          33,
          35,
          41,
          43,
          47,
          49,
          58,
          59,
          61,
          62,
          63,
          64,
          65,
          66,
          67,
          71,
          74,
          81,
          84,
          85,
          86,
          87,
          88,
          89,
          90,
          94
        ],
      ),
      description: Description(
          character: '新', chinesePronunciation: 'xīn', meaning: 'New'),
      examples: [
        Example(word: '新闻', meaning: 'News'),
        Example(word: '新鲜', meaning: 'Fresh'),
        Example(word: '创新', meaning: 'Innovation'),
      ]),
  Picross(
      number: 4,
      game: Game(
        gameNumber: 4,
        correctTiles: [34, 35, 44, 45],
      ),
      description: Description(
          character: 'A', chinesePronunciation: 'ba', meaning: 'Nothing'),
      examples: [
        Example(word: '出租车司机', meaning: 'Nie'),
        Example(word: '出租车司机', meaning: 'Nein'),
        Example(word: '出租车司机', meaning: 'No'),
      ]),
  Picross(
      number: 5,
      game: Game(
        gameNumber: 5,
        correctTiles: [
          3,
          5,
          12,
          13,
          15,
          16,
          17,
          18,
          19,
          22,
          24,
          32,
          34,
          57,
          60,
          61,
          62,
          63,
          65,
          67,
          68,
          70,
          71,
          73,
          75,
          77,
          79,
          80,
          81,
          83,
          85,
          86,
          87,
          88,
          89,
          90,
          91,
          92,
          93,
          95,
          97
        ],
      ),
      description: Description(
          character: '得', chinesePronunciation: 'dé', meaning: 'Obtain'),
      examples: [
        Example(word: '获得', meaning: 'Receive'),
        Example(word: '得到', meaning: 'Get'),
        Example(word: '得罪', meaning: 'Violate law'),
      ]),
  Picross(
      number: 6,
      game: Game(gameNumber: 6, correctTiles: [
        7,
        8,
        13,
        14,
        16,
        17,
        21,
        22,
        24,
        26,
        31,
        34,
        38,
        39,
        41,
        44,
        49,
        50,
        51,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        64,
        70,
        74,
        75,
        76,
        80,
        84,
        86,
        87,
        90,
        94,
        97,
        98
      ]),
      description: Description(
          character: '乐', chinesePronunciation: 'lè', meaning: 'Pleasure'),
      examples: [
        Example(word: '快乐', meaning: 'Happy'),
        Example(word: '乐趣', meaning: 'Joy'),
        Example(word: '乐观', meaning: 'Optimistic'),
      ]),
  Picross(
      number: 7,
      game: Game(gameNumber: 7, correctTiles: [
        1,
        3,
        5,
        10,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        21,
        23,
        25,
        29,
        31,
        35,
        38,
        50,
        51,
        52,
        53,
        54,
        55,
        56,
        57,
        58,
        59,
        60,
        62,
        64,
        65,
        66,
        69,
        70,
        72,
        74,
        76,
        77,
        80,
        82,
        84,
        87,
        88,
        90,
        91,
        92,
        93,
        94,
        97,
        99
      ]),
      description: Description(
          character: '银', chinesePronunciation: 'yín', meaning: 'Silver'),
      examples: [
        Example(word: '银行', meaning: 'Bank'),
        Example(word: '银河', meaning: 'Milky Way'),
        Example(word: '银幕', meaning: 'Screen'),
      ]),
];
